name: Node.js Build using TypeScript (tsc)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn@latest

      - name: Install dependencies
        run: yarn

      - name: Build TypeScript
        run: yarn run build

